version: "3"
services:
  eshop:
    build: .
    ports:
      - "5080:80"
    environment:
      - HOME=C:/Users/Dear User

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    environment:
      - HOME=C:/Users/Dear User
    depends_on:
      - eshop
  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
